#
# Copyright (C) 2023 Apple Inc. All rights reserved.
#
parameters:
  dataset: imagenet
  trainer: ERM
  arch: timm
  model:
    model_name: resnet50d
    pretrained: false
  loss:
    label_smoothing: 0.1
  optim:
    name: sgd
    lr: 0.4
    momentum: 0.9
    weight_decay: 1.e-4
    warmup_length: 5
  epochs: 150
  save_freq: 50
  start_epoch: 0
  batch_size: 1024
  print_freq: 100
  resume: ''
  evaluate: false
  pretrained: false
  dist_url: 'tcp://127.0.0.1:23333'
  dist_backend: 'nccl'
  # Multi-GPU training
  multiprocessing_distributed: true
  world_size: 1
  rank: 0
  workers: 88
  pin_memory: true
  persistent_workers: true
  seed: NULL
  gpu: NULL
  download_data: false  # Set to True to download
  data_path: ''
  artifact_path: ''
  image_augmentation:
    train:
      random_resized_crop:
        size: 224
      rand_augment:  # No horizontal flip when rand-augment is enabled
        enable: true
      to_tensor:
        enable: true
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      random_erase:
        enable: true
        p: 0.25
      mixup:
        enable: true
        alpha: 0.2
        p: 1.0
      cutmix:
        enable: true
        alpha: 1.0
        p: 1.0
    val:
      resize:
        size: 256
      center_crop:
        size: 224
      to_tensor:
        enable: true
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
