#
# Copyright (C) 2023 Apple Inc. All rights reserved.
#
parameters:
  dataset: cifar100
  teacher:
    ensemble: true
    # TODO: Load pretrained
  batch_size: 32
  print_freq: 10
  dist_url: 'tcp://127.0.0.1:23333'
  dist_backend: 'nccl'
  multiprocessing_distributed: true
  world_size: 1
  rank: 0
  workers: 88
  pin_memory: true
  persistent_workers: true
  seed: NULL
  gpu: NULL
  download_data: false  # Set to True to download dataset
  data_path: ''
  artifact_path: ''
  reinforce:
    num_samples: 100
    num_candidates: NULL
    topk: 10
    compress: true
    joblib: false
    gzip: true
    image_augmentation:
      uint8:
        enable: true
      resize:
        size: 224
      random_crop:
        size: 224
        padding: 16
      random_horizontal_flip:
        enable: true
        p: 0.5
      rand_augment:
        enable: true
        p: 1.0
      to_tensor:
        enable: true
      normalize:
        mean: [0.507075159237, 0.4865488733149, 0.440917843367]
        std: [0.267334285879, 0.2564384629170, 0.276150471325]
      random_erase:
        enable: true
        p: 0.25
